Aperture: src/ap_cvector.c File Reference
ap_cvector.c File Reference
cvector implemention
#include "aperture.h"
Functions
bool ap_is_valid_vector (struct AP_Vector *vector)
int ap_vector_data_type_size (struct AP_Vector *vector)
int ap_vector_init (struct AP_Vector *vector, int vector_type)
vector initialize
int ap_vector_free (struct AP_Vector *vector)
Release the memory allocated by vector.
int ap_vector_push_back (struct AP_Vector *vector, const char *data)
Append one data to the back of the vector.
int ap_vector_insert_back (struct AP_Vector *vector, char *start, size_t size)
Insert data at the end of vector.
int ap_vector_remove_data (struct AP_Vector *vector, char *start, char *end, int size)
Detailed Description
cvector implemention
Author
STARRY-S (hxsta.nosp@m.rrys.nosp@m.@gmai.nosp@m.l.co.nosp@m.m)
Definition in file ap_cvector.c.
Function Documentation
ap_is_valid_vector()
bool ap_is_valid_vector (struct AP_Vector * vector)
Check whether vector is initialized or not
Parameters
vector
Returns
bool
Definition at line 118 of file ap_cvector.c.
{
        if (vector == NULL) {
                return false;
        }
        if (vector->data == NULL) {
                return false;
        }
        return true;
}
Referenced by ap_vector_push_back().
ap_vector_data_type_size()
int ap_vector_data_type_size (struct AP_Vector * vector)
Definition at line 16 of file ap_cvector.c.
{
        if (vector == NULL) {
                return 0;
        }
        int size = 0;
        switch (vector->type) {
        case AP_VECTOR_INT:
                size = sizeof(int);
                break;
        case AP_VECTOR_UINT:
                size = sizeof(unsigned int);
                break;
        case AP_VECTOR_FLOAT:
                size = sizeof(float);
                break;
        case AP_VECTOR_SHADER:
                size = sizeof(struct AP_Shader);
                break;
        case AP_VECTOR_MESH:
                size = sizeof(struct AP_Mesh);
                break;
        case AP_VECTOR_MODEL:
                size = sizeof(struct AP_Model);
                break;
        case AP_VECTOR_CAMERA:
                size = sizeof(struct AP_Camera);
                break;
        case AP_VECTOR_AUDIO:
                size = sizeof(struct AP_Audio);
                break;
        case AP_VECTOR_PCREATURE:
                size = sizeof(struct AP_PCreature);
                break;
        case AP_VECTOR_PBARRIER:
                size = sizeof(struct AP_PBarrier);
                break;
        case AP_VECTOR_CHAR:
                size = sizeof(char);
                break;
        case AP_VECTOR_TEXTURE:
                size = sizeof(struct AP_Texture);
                break;
        case AP_VECTOR_VERTEX:
                size = sizeof(struct AP_Vertex);
                break;
        case AP_VECTOR_CHARACTER:
                size = sizeof(struct AP_Character);
                break;
        case AP_VECTOR_LIGHT:
                size = sizeof(struct AP_Light);
                break;
        case AP_VECTOR_POINTER:
                size = sizeof(char*);
                break;
        case AP_VECTOR_UNDEFINED:
        default:
                LOGW("unknow vector type: %d", vector->type);
                return size;
        }
        return size;
}
ap_vector_free()
int ap_vector_free (struct AP_Vector * vector)
Release the memory allocated by vector.
Parameters
vector
Returns
AP_Error_Types
Definition at line 105 of file ap_cvector.c.
{
        if (vector == NULL) {
                return AP_ERROR_INVALID_POINTER;
        }
        AP_FREE(vector->data);
        vector->data = NULL;
        vector->capacity = 0;
        vector->length = 0;
        vector->type = AP_VECTOR_UNDEFINED;
        return 0;
}
Referenced by ap_light_free_all(), and ap_render_finish().
ap_vector_init()
int ap_vector_init (struct AP_Vector * vector, int vector_type)
vector initialize
Parameters
vector pointer points to vector struct object
vector_type AP_VECTOR_Types
Returns
int GE_Types
Definition at line 79 of file ap_cvector.c.
{
        if (vector == NULL) {
                return AP_ERROR_INVALID_POINTER;
        }
        vector->type = vector_type;
        int size = ap_vector_data_type_size(vector);
        vector->capacity = AP_VECTOR_DEFAULT_CAPACITY;
#ifdef AP_TRACE
        char buff[AP_DEFAULT_BUFFER_SIZE] = { 0 };
        sprintf(buff, "%s, type: %d", __func__, vector_type);
        vector->data = AP_MALLOCT(size * AP_VECTOR_DEFAULT_CAPACITY, buff);
#else
        vector->data = AP_MALLOC(size * AP_VECTOR_DEFAULT_CAPACITY);
#endif
        if (vector->data == NULL) {
                LOGE("malloc failed for vector.");
                return AP_ERROR_MALLOC_FAILED;
        }
        memset(vector->data, 0, size * AP_VECTOR_DEFAULT_CAPACITY);
        vector->length = 0;
        return AP_ERROR_SUCCESS;
}
ap_vector_insert_back()
int ap_vector_insert_back (struct AP_Vector * vector, char * start, size_t size)
Insert data at the end of vector.
Parameters
vector
start pointer points to data
size size of data (byte)
Returns
AP_Error_Types
Definition at line 161 of file ap_cvector.c.
{
        if (vector == NULL || start == NULL || size <= 0) {
                return AP_ERROR_INVALID_PARAMETER;
        }
        int type_size = ap_vector_data_type_size(vector);
        if (type_size == 0) {
                return AP_ERROR_INVALID_PARAMETER;
        }
        while (vector->length + (size / type_size) > vector->capacity) {
                vector->data = AP_REALLOC(
                        vector->data,
                        size * vector->capacity * 2
                );
                if (vector->data == NULL) {
                        LOGE("failed to realloc vector memory.");
                        return AP_ERROR_MALLOC_FAILED;
                }
                vector->capacity *= 2;
        }
        int offset = type_size * (vector->length) / (int) sizeof(char);
        char *new_data = vector->data + offset;
        memcpy(new_data, start, size);
        vector->length += (int) size / ap_vector_data_type_size(vector);
        return 0;
}
ap_vector_push_back()
int ap_vector_push_back (struct AP_Vector * vector, const char * data)
Append one data to the back of the vector.
Parameters
vector
data - char* , pointer points to the data,
Returns
AP_Error_Types
Definition at line 131 of file ap_cvector.c.
{
        if (!ap_is_valid_vector(vector) || data == NULL) {
                return AP_ERROR_INVALID_PARAMETER;
        }
        int size = ap_vector_data_type_size(vector);
        if (size == 0) {
                return AP_ERROR_INVALID_PARAMETER;
        }
        if (vector->length == vector->capacity) {
                vector->data = AP_REALLOC(
                        vector->data,
                        size * vector->capacity * 2
                );
                if (vector->data == NULL) {
                        LOGE("failed to realloc vector memory.");
                        return AP_ERROR_MALLOC_FAILED;
                }
                vector->capacity *= 2;
        }
        int offset = size * (vector->length) / (int) sizeof(char);
        char *new_data = vector->data + offset;
        memcpy(new_data, data, size);
        vector->length++;
        return 0;
}
ap_vector_remove_data()
int ap_vector_remove_data (struct AP_Vector * vector, char * start, char * end, int size)
Remove data from vector data
Parameters
start pointer points to the data to be removed
end pointer points to the next data
size size of data to be removed, should be divisible by ap_vector_data_type_size()
Definition at line 190 of file ap_cvector.c.
{
        if (vector == NULL || start == NULL || end == NULL || size <= 0) {
                LOGE("vector remove data failed with null pointer");
                return AP_ERROR_INVALID_PARAMETER;
        }
        if (start >= end) {
                LOGE("vector remove data failed with invalid pointer position");
                return AP_ERROR_INVALID_POINTER;
        }
        unsigned long long start_ull = (unsigned long long) start;
        unsigned long long end_ull   = (unsigned long long)   end;
        if ((end_ull - start_ull) % size != 0) {
                LOGE("vector remove data failed with invalid memory size");
                return AP_ERROR_INVALID_PARAMETER;
        }
        // dest, src, n
        int tmp = vector->length - (size / ap_vector_data_type_size(vector));
        if (tmp < 0) {
                LOGE("vector remove data failed with invalid size");
                return AP_ERROR_INVALID_PARAMETER;
        }
        LOGD("start: %p, end: %p, size: %d", start, end, size);
        memmove(start, end, size);
        vector->length = tmp;
        return 0;
}