Aperture: include/ap_audio.h File Reference
ap_audio.h File Reference
Audio function definitions.
#include "ap_utils.h"
Data Structures
struct AP_Audio
Enumerations
enum AP_Audio_FMT {
AP_AUDIO_FMT_UNKNOWN = 0 , AP_AUDIO_FMT_U8 , AP_AUDIO_FMT_S16 , AP_AUDIO_FMT_S32 ,
AP_AUDIO_FMT_S64 , AP_AUDIO_FMT_FLT , AP_AUDIO_FMT_DBL , AP_AUDIO_FMT_LENGTH
}
Functions
int ap_audio_fmt_ap_2_al (int ap_audio_fmt, int channel)
Convert aperture audio type to OpenAL audio format.
int ap_audio_fmt_av_2_ap (int av_fmt, const char *s)
Convert libavformat audio format to aperture audio format.
int ap_audio_fmt_al_2_ap (int al_fmt)
Convert OpenAL audio format to aperture audio format.
int ap_audio_init ()
Initialize OpenAL, create OpenAL Context.
int ap_audio_free (int id)
release audio by its audio ID
int ap_audio_free_all ()
Close OpenAL device, destroy context.
int ap_audio_load_mp3 (const char *name, unsigned int *id)
Load MPEG-3 format audio into memory and get its audio ID.
int ap_audio_load_wav (const char *name, unsigned int *id)
Load WAV format audio into memory and get its audio ID.
int ap_audio_play (unsigned int id, ap_callback_func_t cb)
Play audio in asynchronized mode.
int ap_audio_pause (unsigned int id)
Pause the audio.
int ap_audio_stop (unsigned int id)
Stop the audio.
struct AP_Audio * ap_audio_get_ptr (unsigned int id)
Get audio struct object pointer.
Detailed Description
Audio function definitions.
Author
Starry Wang (hxsta.nosp@m.rrys.nosp@m.@gmai.nosp@m.l.co.nosp@m.m)
Enumeration Type Documentation
AP_Audio_FMT
enum AP_Audio_FMT
Audio types supported by ap_audio
Enumerator
AP_AUDIO_FMT_U8
unsigned 8 bits
AP_AUDIO_FMT_S16
signed 16 bits
AP_AUDIO_FMT_S32
signed 32 bits
AP_AUDIO_FMT_S64
signed 64bit
AP_AUDIO_FMT_FLT
float
AP_AUDIO_FMT_DBL
double
             {
        AP_AUDIO_FMT_UNKNOWN = 0,
        AP_AUDIO_FMT_U8,
        AP_AUDIO_FMT_S16,
        AP_AUDIO_FMT_S32,
        AP_AUDIO_FMT_S64,
        AP_AUDIO_FMT_FLT,
        AP_AUDIO_FMT_DBL,
        AP_AUDIO_FMT_LENGTH
} AP_Audio_FMT;
Function Documentation
ap_audio_fmt_al_2_ap()
int ap_audio_fmt_al_2_ap (int al_fmt)
Convert OpenAL audio format to aperture audio format.
Parameters
al_fmt
Returns
int aperture audio format, 0 on error
{
        int fmt = AP_AUDIO_FMT_UNKNOWN;
        switch (al_fmt)
        {
        case AL_FORMAT_STEREO8:
        case AL_FORMAT_MONO8:
                fmt = AP_AUDIO_FMT_U8;
                break;
        case AL_FORMAT_MONO16:
        case AL_FORMAT_STEREO16:
                fmt = AP_AUDIO_FMT_S16;
                break;
#ifdef AL_EXT_float32
        case AL_FORMAT_MONO_FLOAT32:
        case AL_FORMAT_STEREO_FLOAT32:
                fmt = AP_AUDIO_FMT_FLT;
                break;
#endif // AL_EXT_float32
#ifdef AL_EXT_double
        case AL_FORMAT_MONO_DOUBLE_EXT:
        case AL_FORMAT_STEREO_DOUBLE_EXT:
                fmt = AP_AUDIO_FMT_DBL;
                break;
#endif  // AL_EXT_double
        default:
                break;
        }
        if (fmt == 0) {
                LOGW("ap_audio_fmt_al_2_ap: unknow format %d", al_fmt);
        }
        return fmt;
}
ap_audio_fmt_ap_2_al()
int ap_audio_fmt_ap_2_al (int ap_audio_fmt, int channel)
Convert aperture audio type to OpenAL audio format.
Parameters
ap_audio_fmt
channel
Returns
int OpenAL audio format, 0 on error
{
        int al_fmt = 0;
        switch (ap_audio_fmt)
        {
        case AP_AUDIO_FMT_U8:
                al_fmt = (channel == 1) ? AL_FORMAT_MONO8 : AL_FORMAT_STEREO8;
                break;
        case AP_AUDIO_FMT_S16:
                al_fmt = (channel == 1) ? AL_FORMAT_MONO16 : AL_FORMAT_STEREO16;
                break;
        case AP_AUDIO_FMT_S32:
                // unsupported yet
                break;
        case AP_AUDIO_FMT_S64:
                // unsupported yet
                break;
        case AP_AUDIO_FMT_FLT:
                al_fmt = (channel == 1)
                        ? AL_FORMAT_MONO_FLOAT32 : AL_FORMAT_STEREO_FLOAT32;
                break;
        case AP_AUDIO_FMT_DBL:
                al_fmt = (channel == 1) ? AL_FORMAT_MONO_DOUBLE_EXT
                        : AL_FORMAT_STEREO_DOUBLE_EXT;
                break;
        default:
                break;
        }
        return al_fmt;
}
ap_audio_fmt_av_2_ap()
int ap_audio_fmt_av_2_ap (int av_fmt, const char * s)
Convert libavformat audio format to aperture audio format.
Parameters
av_fmt
s libavformat format name, can be null, only used for show warning message if format not found
Returns
int aperture audio format, 0 on error
{
        int fmt = 0;
        switch (av_fmt)
        {
        case AV_SAMPLE_FMT_U8:
        case AV_SAMPLE_FMT_U8P:
                fmt = AP_AUDIO_FMT_U8;
                break;
        case AV_SAMPLE_FMT_S16:
        case AV_SAMPLE_FMT_S16P:
                fmt = AP_AUDIO_FMT_S16;
                break;
        case AV_SAMPLE_FMT_S32:
        case AV_SAMPLE_FMT_S32P:
                fmt = AP_AUDIO_FMT_S32;
                break;
        case AV_SAMPLE_FMT_FLT:
        case AV_SAMPLE_FMT_FLTP:
                fmt = AP_AUDIO_FMT_FLT;
                break;
        case AV_SAMPLE_FMT_DBL:
        case AV_SAMPLE_FMT_DBLP:
                fmt = AP_AUDIO_FMT_DBL;
                break;
        case AV_SAMPLE_FMT_S64:
        case AV_SAMPLE_FMT_S64P:
                fmt = AP_AUDIO_FMT_S64;
        default:
                break;
        }
        if (fmt == 0) {
                LOGW("ap_audio_fmt_av_2_ap: unrecognized format %d %s",
                        av_fmt, s);
        }
        return fmt;
}
ap_audio_free()
int ap_audio_free (int id)
release audio by its audio ID
Parameters
id
Returns
int AP_Error_Types
{
        if (id <= 0) {
                return AP_ERROR_INVALID_PARAMETER;
        }
        // Stop all playing audios firstlly, then release memories unreleased
        // then close OpenAL
        struct AP_Audio *ptr, *data = NULL;
        data = (struct AP_Audio*) audio_vector.data;
        for (int i = 0; i < audio_vector.length; ++i) {
                ptr = data + i;
                if (ptr->id != id) {
                        continue;
                }
                ap_audio_stop_ptr(ptr);
                ap_audio_release_ptr(ptr);
                ap_vector_remove_data(
                        &audio_vector,
                        (char*) (ptr),
                        (char*) (ptr + 1),
                        sizeof(struct AP_Audio)
                );
                break;
        }
        return 0;
}
ap_audio_free_all()
int ap_audio_free_all ()
Close OpenAL device, destroy context.
Returns
AP_Error_Types
{
        // Stop all playing audios firstlly, then release memories unreleased
        // then close OpenAL
        struct AP_Audio *ptr, *data = NULL;
        data = (struct AP_Audio*) audio_vector.data;
        for (int i = 0; i < audio_vector.length; ++i) {
                ptr = data + i;
                ap_audio_stop_ptr(ptr);
                ap_audio_release_ptr(ptr);
        }
        ap_vector_free(&audio_vector);
        device = alcGetContextsDevice(context);
        alcMakeContextCurrent(NULL);
        alcDestroyContext(context);
        alcCloseDevice(device);
#if !AP_PLATFORM_ANDROID
        alutExit();
#endif
        return 0;
}
ap_audio_get_ptr()
struct AP_Audio * ap_audio_get_ptr (unsigned int id)
Get audio struct object pointer.
Parameters
id
Returns
struct AP_Audio*
{
        if (id == 0) {
                return 0;
        }
        struct AP_Audio *data = (struct AP_Audio*) audio_vector.data;
        struct AP_Audio *ptr = NULL;
        for (int i = 0; i < audio_vector.length; ++i) {
                ptr = data + i;
                if (ptr->id == id) {
                        return ptr;
                }
        }
        LOGW("audio id %u not found", id);
        return NULL;
}
Referenced by ap_audio_pause(), ap_audio_play(), and ap_audio_stop().
ap_audio_init()
int ap_audio_init ()
Initialize OpenAL, create OpenAL Context.
Returns
AP_Error_Types
{
#if !AP_PLATFORM_ANDROID
        int ret = 0;
        ret = alutInitWithoutContext(NULL, NULL);
        if (ret == 0) {
                ap_audio_check_alut("alutInitWithoutContext");
                return AP_ERROR_INIT_FAILED;
        }
#endif
        if (device_name == NULL) {
                device_name = alcGetString(NULL, ALC_DEVICE_SPECIFIER);
                LOGD("ap_audio device name: %s", device_name);
        }
        if (device == NULL) {
                device = alcOpenDevice(device_name);
                if (!device) {
                        LOGE("failed to open device name %s", device_name);
                        return AP_ERROR_INIT_FAILED;
                }
        }
        // Clear the error buffer
        alGetError();
        if (context == NULL) {
                context = alcCreateContext(device, NULL);
                if (!alcMakeContextCurrent(context)) {
                        ap_audio_check("alcMakeContextCurrent");
                        return AP_ERROR_INIT_FAILED;
                }
        }
        alListener3f(AL_POSITION, 0, 0, 1.0f);
        ap_audio_check("alListener3f");
        alListener3f(AL_VELOCITY, 0, 0, 0);
        ap_audio_check("alListener3f");
        ALfloat orientation[] = { 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 0.0f };
        alListenerfv(AL_ORIENTATION, orientation);
        ap_audio_check("alListenerfv");
        // initialize vector
        ap_vector_init(&audio_vector, AP_VECTOR_AUDIO);
        return 0;
}
ap_audio_load_mp3()
int ap_audio_load_mp3 (const char * name, unsigned int * id)
Load MPEG-3 format audio into memory and get its audio ID.
Parameters
name [in] file name
id [out] audio ID
See also
ap_audio_load_wav
Returns
int AP_Error_Types
{
        if (id == NULL) {
                return AP_ERROR_INVALID_PARAMETER;
        }
        struct AP_Audio *audio = NULL;
        *id = 0;
        int ret = ap_audio_open_file_mp3_ptr(name, &audio);
        if (audio == NULL || ret != 0) {
                AP_CHECK(ret);
                LOGE("ap_audio_load_mp3 failed");
                return ret;
        }
        audio->id = audio_vector.length + 1;
        LOGT("load audio name: %s", audio->name);
        ret = ap_vector_push_back(&audio_vector, (const char*) audio);
        AP_CHECK(ret);
        if (ret != 0) {
                ap_audio_release_ptr(audio);
                AP_FREE(audio);
        } else {
                AP_FREE(audio);
                *id = audio_vector.length;
        }
        return ret;
}
ap_audio_load_wav()
int ap_audio_load_wav (const char * name, unsigned int * id)
Load WAV format audio into memory and get its audio ID.
Parameters
name [in] file name
id [out] audio ID
See also
ap_audio_load_mp3
Returns
int AP_Error_Types
{
        if (id == NULL) {
                return AP_ERROR_INVALID_PARAMETER;
        }
        struct AP_Audio *audio = NULL;
        *id = 0;
        int ret = ap_audio_open_file_WAV_ptr(name, &audio);
        if (audio == NULL || ret != 0) {
                return ret;
        }
        audio->id = audio_vector.length + 1;
        ret = ap_vector_push_back(&audio_vector, (const char*) audio);
        if (ret != 0) {
                ap_audio_release_ptr(audio);
                AP_CHECK(ret);
                AP_FREE(audio);
        } else {
                AP_FREE(audio);
                *id = audio_vector.length;
        }
        return ret;
}
ap_audio_pause()
int ap_audio_pause (unsigned int id)
Pause the audio.
Parameters
id
Returns
int
{
        struct AP_Audio *ptr = ap_audio_get_ptr(id);
        return ap_audio_pause_ptr(ptr);
}
ap_audio_play()
int ap_audio_play (unsigned int id, ap_callback_func_t cb)
Play audio in asynchronized mode.
Parameters
id audio ID
cb callback function, can be NULL
Returns
int
{
        struct AP_Audio *ptr = ap_audio_get_ptr(id);
        return ap_audio_play_ptr(ptr, cb);
}
ap_audio_stop()
int ap_audio_stop (unsigned int id)
Stop the audio.
Parameters
id
Returns
int
{
        struct AP_Audio *ptr = ap_audio_get_ptr(id);
        return ap_audio_stop_ptr(ptr);
}